<a href="https://colab.research.google.com/github/kholikulovelyor/Data-Darsliklari-uchun/blob/2-modul.-DATA-ANALYSIS-PANDAS-KUTUBXONASI/Mohirdev_Pandas_Funksiyalarni_qo'llash.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame(np.random.randn(3,4), index=list('abc'), columns=['Olma','Anor','Qovun','Anjir'])
df

       Olma      Anor     Qovun     Anjir
a  0.387421  0.665773  0.149483 -0.972222
b  0.217597 -0.410364  0.272751  0.112614
c  0.579501  1.203246 -0.628576 -0.655535

In [3]:
np.abs(df)

       Olma      Anor     Qovun     Anjir
a  0.387421  0.665773  0.149483  0.972222
b  0.217597  0.410364  0.272751  0.112614
c  0.579501  1.203246  0.628576  0.655535

In [7]:
np.round(df)

   Olma  Anor  Qovun  Anjir
a   0.0   1.0    0.0   -1.0
b   0.0  -0.0    0.0    0.0
c   1.0   1.0   -1.0   -1.0

In [8]:
df.mean()

Olma     0.394840
Anor     0.486218
Qovun   -0.068781
Anjir   -0.505047
dtype: float64

In [9]:
df.apply(np.abs)

       Olma      Anor     Qovun     Anjir
a  0.387421  0.665773  0.149483  0.972222
b  0.217597  0.410364  0.272751  0.112614
c  0.579501  1.203246  0.628576  0.655535

In [10]:
df.apply(sum)

Olma     1.184519
Anor     1.458654
Qovun   -0.206342
Anjir   -1.515142
dtype: float64

In [11]:
df.apply(sum, axis=1)

a    0.230455
b    0.192597
c    0.498636
dtype: float64

In [12]:
f = lambda x: x.max() - x.min()

In [19]:
df.mean()

Olma     0.394840
Anor     0.486218
Qovun   -0.068781
Anjir   -0.505047
dtype: float64

In [13]:
df.apply(f)

Olma     0.361904
Anor     1.613610
Qovun    0.901327
Anjir    1.084836
dtype: float64

In [14]:
df.apply(lambda x: x.max() - x.min())

Olma     0.361904
Anor     1.613610
Qovun    0.901327
Anjir    1.084836
dtype: float64

In [16]:
def foo(x):
  return pd.Series([x.min(), x.max()], index = ['min', 'max'])

In [17]:
df.apply(foo)

         Olma      Anor     Qovun     Anjir
min  0.217597 -0.410364 -0.628576 -0.972222
max  0.579501  1.203246  0.272751  0.112614

In [20]:
df = pd.DataFrame(np.arange(1,13).reshape(3,4), index=list('abc'), columns=['Olma','Anor','Qovun','Anjir'])
df

   Olma  Anor  Qovun  Anjir
a     1     2      3      4
b     5     6      7      8
c     9    10     11     12

In [21]:
df.applymap(lambda x: x*x)

   Olma  Anor  Qovun  Anjir
a     1     4      9     16
b    25    36     49     64
c    81   100    121    144